In [1]:
# Loading packages Numpy and Pandas
import numpy as np
import pandas as pd
#Load Driving File and keep first column as index
drive = pd.read_csv('../uri_csc593/dataset/drive.csv', index_col=0)

In [2]:
drive.head()

,Altitude[m],HV Battery Current[A],HV Battery SOC[%],HV Battery Voltage[V],Is Driving[bool],Latitude[deg],Longitude[deg],OAT[degC],Vehicle Speed[km/h]
Timestamp(ms),,,,,,,,,
0,0.000000,0.00,0.0,0.0,0,0.000000,0.000000,0,0
500,0.000000,0.00,0.0,0.0,0,0.000000,0.000000,0,0
1500,0.000000,-1.25,33.0,319.0,1,0.000000,0.000000,10,0
2500,0.000000,-1.25,33.0,319.0,1,0.000000,0.000000,10,0
3500,74.400002,-1.25,33.0,319.0,1,41.489159,-71.521751,10,0

In [3]:
# Remove unwanted characters from Columns
drive.columns = drive.columns.str.replace("[", "_")
drive.columns = drive.columns.str.replace("]","")
drive.columns = drive.columns.str.replace("/","")
drive.columns = drive.columns.str.replace("%","Pctg")

In [4]:
# Deleting rows where GPS signal in the beginning was lost
drive = drive[drive.Longitude_deg != 0]

In [5]:
drive.head()

,Altitude_m,HV Battery Current_A,HV Battery SOC_Pctg,HV Battery Voltage_V,Is Driving_bool,Latitude_deg,Longitude_deg,OAT_degC,Vehicle Speed_kmh
Timestamp(ms),,,,,,,,,
3500,74.400002,-1.25,33.0,319.00,1,41.489159,-71.521751,10,0
4500,74.400002,-13.75,33.0,318.50,1,41.489159,-71.521751,10,2
5500,74.400002,-13.75,33.0,318.50,1,41.489159,-71.521751,10,2
6500,74.400002,-10.75,33.0,318.75,1,41.489159,-71.521751,10,3
7500,74.400002,-15.50,33.0,318.25,1,41.489159,-71.521751,10,6

In [6]:
# Averages for each column
drive.mean()

Altitude_m               36.321847
HV Battery Current_A    -20.659444
HV Battery SOC_Pctg      20.609683
HV Battery Voltage_V    314.500299
Is Driving_bool           1.000000
Latitude_deg             41.453263
Longitude_deg           -71.545222
OAT_degC                  8.942020
Vehicle Speed_kmh        48.102510
dtype: float64

In [7]:
# Average for just one column
drive[['HV Battery Voltage_V']].mean(axis=0)

HV Battery Voltage_V    314.500299
dtype: float64

In [8]:
# Alternative way
drive['HV Battery Voltage_V'].mean()

314.5002988643156

In [9]:
# Create list of grouped items
grouped = drive['Vehicle Speed_kmh'].groupby(drive['Is Driving_bool'])
grouped

In [10]:
grouped.mean()

Is Driving_bool
1    48.10251
Name: Vehicle Speed_kmh, dtype: float64

In [11]:
# Group items and get mean
drive.groupby(['Is Driving_bool'])[['Vehicle Speed_kmh']].mean()

                 Vehicle Speed_kmh
Is Driving_bool
1                         48.10251

In [12]:
# Add column with speed as m_s
drive['Vehicle Speed_m_s'] = drive['Vehicle Speed_kmh']/3.6
# Add column with Acceleration
drive['Acceleration'] = drive['Vehicle Speed_m_s'] - drive['Vehicle Speed_m_s'].shift()
# Add Column with Jerk
# Needs to be added!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# Add column with distance travelled in that second
drive['Dist_in_s'] = drive['Vehicle Speed_m_s']/1609.344
# Add column with cumulative distance
drive['Cumsum_Dist'] = drive['Dist_in_s'].cumsum()
drive.tail(50)

,Altitude_m,HV Battery Current_A,HV Battery SOC_Pctg,HV Battery Voltage_V,Is Driving_bool,Latitude_deg,Longitude_deg,OAT_degC,Vehicle Speed_kmh,Vehicle Speed_m_s,Dist_in_s,Cumsum_Dist
Timestamp(ms),,,,,,,,,,,,
3299500,62.700001,-0.75,11.0,313.50,1,41.486449,-71.524386,9,17,4.722222,0.002934,27.733522
3300500,64.599998,6.25,11.0,313.75,1,41.486029,-71.524547,9,16,4.444444,0.002762,27.736284
3301500,64.599998,9.00,11.0,314.00,1,41.486029,-71.524547,9,14,3.888889,0.002416,27.738700
3302500,64.599998,7.50,11.0,314.00,1,41.486029,-71.524547,9,11,3.055556,0.001899,27.740599
3303500,64.599998,-3.25,11.0,313.50,1,41.486029,-71.524547,9,10,2.777778,0.001726,27.742325
3304500,64.599998,-23.00,11.0,312.50,1,41.486029,-71.524547,9,11,3.055556,0.001899,27.744224
3305500,64.599998,-26.00,11.0,312.25,1,41.486029,-71.524547,9,13,3.611111,0.002244,27.746468
3306500,64.599998,-29.00,10.5,312.25,1,41.486029,-71.524547,9,16,4.444444,0.002762,27.749229
3307500,64.599998,-28.50,10.5,312.00,1,41.486029,-71.524547,9,18,5.000000,0.003107,27.752336
3308500,64.599998,0.00,10.5,313.25,1,41.486029,-71.524547,9,19,5.277778,0.003279,27.755616
3309500,64.599998,-7.50,10.5,313.00,1,41.486029,-71.524547,9,19,5.277778,0.003279,27.758895
3310500,64.000000,-6.50,10.5,313.00,1,41.485883,-71.524171,9,20,5.555556,0.003452,27.762347
3311500,64.000000,-10.50,10.5,313.00,1,41.485883,-71.524171,9,20,5.555556,0.003452,27.765799
3312500,64.000000,-6.50,10.5,313.50,1,41.485883,-71.524171,9,19,5.277778,0.003279,27.769079
3313500,64.000000,-7.00,10.5,313.50,1,41.485883,-71.524171,9,18,5.000000,0.003107,27.772185
3314500,64.000000,-1.00,10.5,313.75,1,41.485883,-71.524171,9,16,4.444444,0.002762,27.774947
3315500,64.000000,-0.75,10.5,313.50,1,41.485883,-71.524171,9,15,4.166667,0.002589,27.777536
3316500,64.000000,6.50,10.5,314.00,1,41.485883,-71.524171,9,9,2.500000,0.001553,27.779090
3317500,64.000000,8.75,10.5,314.25,1,41.485883,-71.524171,9,9,2.500000,0.001553,27.780643
3318500,64.000000,-1.00,10.5,313.50,1,41.485883,-71.524171,9,0,0.000000,0.000000,27.780643
3319500,64.000000,-6.25,10.5,313.25,1,41.485883,-71.524171,9,0,0.000000,0.000000,27.780643
3320500,64.000000,-6.25,10.5,313.25,1,41.485883,-71.524171,9,0,0.000000,0.000000,27.780643
3321500,64.000000,-6.25,10.5,313.25,1,41.485883,-71.524171,9,0,0.000000,0.000000,27.780643
3322500,64.000000,-6.25,10.5,313.25,1,41.485883,-71.524171,9,0,0.000000,0.000000,27.780643
3323500,64.000000,-6.25,10.5,313.25,1,41.485883,-71.524171,9,0,0.000000,0.000000,27.780643
3324500,64.000000,-6.25,10.5,313.25,1,41.485883,-71.524171,9,0,0.000000,0.000000,27.780643
3325500,64.000000,-6.25,10.5,313.25,1,41.485883,-71.524171,9,0,0.000000,0.000000,27.780643
3326500,64.000000,-6.25,10.5,313.25,1,41.485883,-71.524171,9,0,0.000000,0.000000,27.780643
3327500,64.000000,-6.25,10.5,313.25,1,41.485883,-71.524171,9,0,0.000000,0.000000,27.780643
3328500,64.000000,-6.25,10.5,313.25,1,41.485883,-71.524171,9,0,0.000000,0.000000,27.780643
3329500,64.000000,-0.75,10.5,313.50,1,41.485883,-71.524171,9,0,0.000000,0.000000,27.780643
3330500,64.000000,-0.75,10.5,313.50,1,41.485883,-71.524171,9,0,0.000000,0.000000,27.780643
3331500,64.000000,-0.75,10.5,313.50,1,41.485883,-71.524171,9,0,0.000000,0.000000,27.780643
3332500,64.000000,-0.75,10.5,313.50,1,41.485883,-71.524171,9,0,0.000000,0.000000,27.780643
3333500,64.000000,-0.75,10.5,313.50,1,41.485883,-71.524171,9,0,0.000000,0.000000,27.780643
3334500,64.000000,-0.75,10.5,313.50,1,41.485883,-71.524171,9,0,0.000000,0.000000,27.780643
3335500,64.000000,-0.75,10.5,313.50,1,41.485883,-71.524171,9,0,0.000000,0.000000,27.780643
3336500,64.000000,-0.75,10.5,313.50,1,41.485883,-71.524171,9,0,0.000000,0.000000,27.780643
3337500,64.000000,-0.75,10.5,313.50,1,41.485883,-71.524171,9,0,0.000000,0.000000,27.780643
3338500,64.000000,-0.75,10.5,313.50,1,41.485883,-71.524171,9,0,0.000000,0.000000,27.780643
3339500,64.000000,-0.75,10.5,313.75,1,41.485883,-71.524171,9,0,0.000000,0.000000,27.780643
3340500,64.000000,-0.75,10.5,313.75,1,41.485883,-71.524171,9,0,0.000000,0.000000,27.780643
3341500,64.000000,-0.75,10.5,313.75,1,41.485883,-71.524171,9,0,0.000000,0.000000,27.780643
3342500,64.000000,-0.75,10.5,313.75,1,41.485883,-71.524171,9,0,0.000000,0.000000,27.780643
3343500,64.000000,-0.75,10.5,313.75,1,41.485883,-71.524171,9,0,0.000000,0.000000,27.780643
3344500,64.000000,-0.75,10.5,313.75,1,41.485883,-71.524171,9,0,0.000000,0.000000,27.780643
3345500,64.000000,-0.75,10.5,313.75,1,41.485883,-71.524171,9,0,0.000000,0.000000,27.780643
3346500,64.000000,-0.75,10.5,313.75,1,41.485883,-71.524171,9,0,0.000000,0.000000,27.780643
3347500,64.000000,-0.75,10.5,313.75,1,41.485883,-71.524171,9,0,0.000000,0.000000,27.780643
3348500,64.000000,-0.75,10.5,313.75,1,41.485883,-71.524171,9,0,0.000000,0.000000,27.780643

In [13]:
drive['Dist_in_s'].cumsum()

Timestamp(ms)
3500        0.000000
4500        0.000345
5500        0.000690
6500        0.001208
7500        0.002244
8500        0.003797
9500        0.005523
10500       0.007077
11500       0.007422
12500       0.007767
13500       0.008285
14500       0.008803
15500       0.009321
16500       0.009666
17500       0.010011
18500       0.010356
19500       0.010701
20500       0.011047
21500       0.011564
22500       0.012427
23500       0.013808
24500       0.015879
25500       0.018814
26500       0.022956
27500       0.028307
28500       0.034693
29500       0.041943
30500       0.049882
31500       0.057995
32500       0.066452
             ...
3319500    27.780643
3320500    27.780643
3321500    27.780643
3322500    27.780643
3323500    27.780643
3324500    27.780643
3325500    27.780643
3326500    27.780643
3327500    27.780643
3328500    27.780643
3329500    27.780643
3330500    27.780643
3331500    27.780643
3332500    27.780643
3333500    27.780643
3334500    27.780643
3335500    27.780643
3336500    27.780643
3337500    27.780643
3338500    27.780643
3339500    27.780643
3340500    27.780643
3341500    27.780643
3342500    27.780643
3343500    27.780643
3344500    27.780643
3345500    27.780643
3346500    27.780643
3347500    27.780643
3348500    27.780643
Name: Dist_in_s, Length: 3346, dtype: float64

In [14]:
kW = drive['HV Battery Current_A'] * drive['HV Battery Voltage_V']
drive['kw'] = kW

In [15]:
drive.head()

,Altitude_m,HV Battery Current_A,HV Battery SOC_Pctg,HV Battery Voltage_V,Is Driving_bool,Latitude_deg,Longitude_deg,OAT_degC,Vehicle Speed_kmh,Vehicle Speed_m_s,Dist_in_s,Cumsum_Dist,kw
Timestamp(ms),,,,,,,,,,,,,
3500,74.400002,-1.25,33.0,319.00,1,41.489159,-71.521751,10,0,0.000000,0.000000,0.000000,-398.7500
4500,74.400002,-13.75,33.0,318.50,1,41.489159,-71.521751,10,2,0.555556,0.000345,0.000345,-4379.3750
5500,74.400002,-13.75,33.0,318.50,1,41.489159,-71.521751,10,2,0.555556,0.000345,0.000690,-4379.3750
6500,74.400002,-10.75,33.0,318.75,1,41.489159,-71.521751,10,3,0.833333,0.000518,0.001208,-3426.5625
7500,74.400002,-15.50,33.0,318.25,1,41.489159,-71.521751,10,6,1.666667,0.001036,0.002244,-4932.8750